#!/bin/sh

CONFIG="${XDG_CONFIG_HOME:-${HOME}/.config}/rawide"
BIN="${0}"

export TEXTDOMAIN=rawide
export TEXTDOMAINDIR=/usr/share/locale

if type -p gettext > /dev/null
then
	function _() {
		gettext "$@"
	}
else
	function _() {
		printf "$@"
	}
fi

function help() {
	printf "`_ "\
Usage: %s (init | open {PROJECT}) [OPTIONS]

Commands:
	help           Show this help
	init           Create a new shortcut for a project
	open {PROJECT} Open a project to work (shouldn't need be called directly)
"`\n" "${BIN##*/}"
}

function fail() {
	FORMAT="${1}\n"
	shift
	printf "${FORMAT}" "$@" >&2
	exit 1
}

[ -d "${CONFIG}" ] || mkdir -p "${CONFIG}"

function findOpen() {
	if [ -z "${OPEN}" ]
	then
		[ -f "${HQ}/Makefile" ] && OPEN="Makefile"
		[ -n "${OPEN}" ] || OPEN="."
	fi
}

function def() {
	local VAL
	eval "VAL=\"\$${1}\""
	printf "%s='%s'\n" "${1}" "${VAL}"
}

function init() {
	HQ="${PWD%/}"
	NAME="${HQ##*/}"
	OPEN=
	ASK=y
	while [ -n "${1}" ]
	do
		case "${1}" in
			-o)
				if [ -n "${2}" ]
				then
					OPEN="${2}"
					shift 1
				else
					fail "`_ "-o option takes the name of a file as a parameter"`"
				fi;;
			-y)
				ASK=n;;
			*)
				fail "`_ "What do you mean, '%s' ?"`" "${1}"
		esac
		shift 1
	done
	findOpen
	if [ n != "${ASK}" ]
	then
		printf "`_ "The name of your project seems to be '%s'. Is that correct ? (Type another name if you're dissatisfied and press [Enter] to confirm)"`\n" "${NAME}"
		read NEWNAME
		[ -z "${NEWNAME}" ] || NAME="${NEWNAME}"
	fi
	def HQ > "${CONFIG}/${NAME}"
	[ -z "${OPEN}" ] || def OPEN >> "${CONFIG}/${NAME}"
cat <<EOF > "./${NAME}.desktop"
[Desktop Entry]
Icon=applications-development
Exec=${BIN} open "%c"
Type=Application
Categories=Development;
Name=${NAME}
Comment=Start coding already !
EOF
	chmod +x "./${NAME}.desktop"
}

function open() {
	. "${CONFIG}/${1}"
	findOpen
	cd "${HQ}"
	xdg-open . & ${TERMINAL} & ${EDITOR} "${OPEN}"
}

case ${1} in
	-h|--help|help) help;;
	init)
		init;;
	open)
		[ -n "${2}" ] || fail "`_ "'open' command takes the name of the project to open as a parameter"`"
		TARGET="${2#\'}"
		TARGET="${TARGET%\'}"
		open "${TARGET}";;
esac

